//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Employee_Version1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpenseID { get; set; }
        public int BudgetID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public int CategoryID { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Budget Budget { get; set; }
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
