//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Employee_Version1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Version3_LoanEntities5 : DbContext
    {
        public Version3_LoanEntities5()
            : base("name=Version3_LoanEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomersInLoan> CustomersInLoans { get; set; }
        public virtual DbSet<IncomeRangeRate> IncomeRangeRates { get; set; }
        public virtual DbSet<LoanApplication> LoanApplications { get; set; }
        public virtual DbSet<LoanProduct> LoanProducts { get; set; }
        public virtual DbSet<OccupationGroupRate> OccupationGroupRates { get; set; }
        public virtual DbSet<RepaymentAccount> RepaymentAccounts { get; set; }
        public virtual DbSet<RepaymentSchedule> RepaymentSchedules { get; set; }
        public virtual DbSet<TransactionLog> TransactionLogs { get; set; }
    
        public virtual ObjectResult<CalculateRepaymentStatus_Result> CalculateRepaymentStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalculateRepaymentStatus_Result>("CalculateRepaymentStatus");
        }
    
        public virtual int GenerateRepaymentSchedules(Nullable<int> loanApplicationID)
        {
            var loanApplicationIDParameter = loanApplicationID.HasValue ?
                new ObjectParameter("LoanApplicationID", loanApplicationID) :
                new ObjectParameter("LoanApplicationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateRepaymentSchedules", loanApplicationIDParameter);
        }
    
        public virtual int UpdateRepaymentStatusForCurrentMonth()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateRepaymentStatusForCurrentMonth");
        }
    }
}
