//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Employee_Version1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanProduct()
        {
            this.LoanApplications = new HashSet<LoanApplication>();
        }
    
        public int LoanProductID { get; set; }
        public string ProductName { get; set; }
        public decimal InterestRate { get; set; }
        public int LoanTerm { get; set; }
        public decimal MaxLoanAmount { get; set; }
        public decimal MinLoanAmount { get; set; }
        public string ProductDescription { get; set; }
        public string ImageFileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanApplication> LoanApplications { get; set; }
    }
}
