//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Employee_Version1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupationGroupRate
    {
        public int OccupationGroupRateID { get; set; }
        public string OccupationGroup { get; set; }
        public string SubGroup { get; set; }
        public Nullable<decimal> AdjustmentRate { get; set; }
    }
}
