//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Employee_Version1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepaymentAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RepaymentAccount()
        {
            this.LoanApplications = new HashSet<LoanApplication>();
            this.TransactionLogs = new HashSet<TransactionLog>();
        }
    
        public int RepaymentAccountID { get; set; }
        public string AccountNumber { get; set; }
        public decimal TotalRepaymentAmount { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanApplication> LoanApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLog> TransactionLogs { get; set; }
    }
}
