//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題Employee_Version1.Models.Loan
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanApplication()
        {
            this.RepaymentSchedules = new HashSet<RepaymentSchedule>();
        }
    
        public int LoanApplicationID { get; set; }
        public int CustomerID { get; set; }
        public int LoanProductID { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public decimal LoanAmount { get; set; }
        public string LoanStatus { get; set; }
        public string EconomicProof { get; set; }
        public string DisbursementAccount { get; set; }
        public Nullable<int> RepaymentMonths { get; set; }
        public Nullable<decimal> TotalRepaymentAmount { get; set; }
        public Nullable<int> RepaymentAccountID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual LoanProduct LoanProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepaymentSchedule> RepaymentSchedules { get; set; }
        public virtual RepaymentAccount RepaymentAccount { get; set; }
    }
}
